export enum TaskAuditAction {
  TASK_CREATED = "TASK_CREATED",
  TASK_ASSIGNED = "TASK_ASSIGNED",
  TASK_COMPLETED = "TASK_COMPLETED",
  DUE_DATE_UPDATED = "DUE_DATE_UPDATED",
  TASK_OVERDUE_ESCALATED = "TASK_OVERDUE_ESCALATED",
  TASK_CANCELLED="TASK_CANCELLED",
  TASK_AUTO_CLOSED = "TASK_AUTO_CLOSED",
  TASK_DUEDATE_UPDATED="TASK_DUEDATE_UPDATED",
  TASK_UPDATED="TASK_UPDATED",
  DUE_REMINDER_SENT="DUE_REMINDER_SENT",
  
}